routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=> ['web' => 'auth']],function (){


Route::get('newsa/{id}', 'HomeController@orderByDrop');
Route::get('/live_search/action', 'HomeController@action')->name('live_search.action');

	Route::resource('product','product');
Route::resource('category','cate');
	Route::resource('events','eventsConroller');

	Route::get('home',function(){
if(Auth::user()->admin == 0){
	return view('home');
}else{
	$user=\App\User::all();
return 	 view('admin.index', compact('user'));

}
	});
		});

// fornt 
Route::get('/', 'FrontController@index');
Route::post('sreachpage', 'FrontController@sareac');
Route::get('mail', 'FrontController@maila');
Route::get('event', 'FrontController@events');
Route::get('About', 'FrontController@About');
Route::get('products', 'FrontController@product');
Route::get('cate/{id}', 'FrontController@cate');
Route::get('Detail/{id}', 'FrontController@Detail');
Route::get('read/{id}/{por}', 'FrontController@read');

Route::get('add/{id}', 'ca@addcart');
Route::get('cart', 'ca@index');
Route::get('remove/{id}','ca@destroy');
Route::PUT('/Cart/update/{id}','ca@update');
//paym
Route::post('pay', 'PaymentController@paywithpaypal');
Route::get('stauts','PaymentController@stauts');
Route::get('Canceled','PaymentController@Canceled');

app/Http/Controllers/product.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\pro;
use Image;
 use App\category;
use Illuminate\Support\Facades\Auth;

class product extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->admin == 1){
        $products=pro::paginate(5);
        
        return view('admin.product.index',compact("products"));}

        else 
        {
            return view('error404');

                }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
                if(Auth::user()->admin == 1){

        $cat=category::pluck('name','id');
        return view('admin.product.create',compact('cat'));
        }
        else 
        {
            return view('error404');

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
'pro_name'=>'required',
'pro_code'=>'required',
'pro_price'=>'required',
'pro_info'=>'required',
'spl_price'=>'required',
'image'=>'required|mimes:jpg,png,jpeg|max:1000',

        ]);
        $pro=new pro();
            $pro->pro_name=$request->input('pro_name');

            $pro->pro_code=$request->input('pro_code');

            $pro->pro_price=$request->input('pro_price');

            $pro->pro_info=$request->input('pro_info');
            $pro->stook=$request->input('stook');

            $pro->categories_id=$request->input('categories_id');
            $pro->spl_price=$request->input('spl_price');
                        $pro->offier=$request->input('offier');

           

        if($request->hasFile('image')){
          $img=$request->image;
    $filename=time() ."_".$img->getClientOriginalName();
    $localtion=public_path('image/'.$filename);
      //$img->move($localtion);
      image::make($img)->resize(1000,1000)->save($localtion);
     
      }

      $pro->image=$filename; 

    $pro->save();
    return redirect('home');
    }

    /**
     * Display toffierhe specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                if(Auth::user()->admin == 1){

        $products=pro::find($id);
        return view('admin.product.edit',compact('products'));
   }
        else 
        {
            return view('error404');

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
   if(Auth::user()->admin == 1){
        $productdelete=pro::find($id);   
        unlink('image/'.$productdelete->image);

      $productdelete->delete();
      return back();;   
    } 

        else 
        {
            return view('error404');

        }
}

}

resources/views/admin/product/create.blade.php
@extends('admin.master')
@section('title','Add product')
@section('content')
	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 text-center">
        <h1>Add product</h1>
<div class="col-md-6">
	<div class="panel-body">
		<form action="{{route('product.store')}}" method="post" role="form"  enctype="multipart/form-data">
			<legend>Add product</legend>
			{{csrf_field()}}
			<div class="form-group {{$errors->has('pro_name')?'has-error':''}}">
				<label for="pro_name">product Name</label>
				<input type="text" name="pro_name" id="pro_name"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_name')}}</span>
			</div>
				 <div class="form-group {{$errors->has('pro_code')?'has-error':''}}">
				<label for="pro_code">code</label>
				<input type="text" name="pro_code" id="pro_code"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_code')}}</span>
			     </div>
				   <div class="form-group {{$errors->has('pro_price')?'has-error':''}}">
				<label for="pro_price">price</label>
				<input type="text" name="pro_price" id="pro_price"  class="form-control" >
				<span class="text-danger">{{$errors->first('pro_price')}}</span>
			       </div>

			          <div class="form-group {{$errors->has('stook')?'has-error':''}}">
				<label for="stook">stook</label>
				<input type="text" name="stook" id="stook"  class="form-control" >
				<span class="text-danger">{{$errors->first('stook')}}</span>
			       </div>



				    <div class="form-group {{$errors->has('pro_info')?'has-error':''}}">
				<label for="pro_info">Description</label>
				<textarea  name="pro_info" id="pro_info"  class="form-control"  rows="5"></textarea> 
				<span class="text-danger">{{$errors->first('pro_info')}}</span>
			        </div>


    <div class="form-group {{$errors->has('categories_id')?'has-error':''}}">
				<label for="categories_id">Catgeroy</label>

				<select name="categories_id" id="categories_id">
					@foreach($cat as  $id=>$cats)
					<option value="{{$id}}">{{$cats}}</option>
					@endforeach
				</select>

				<span class="text-danger">{{$errors->first('categories_id')}}</span>
			        </div>
 

    <div class="form-group {{$errors->has('offier')?'has-error':''}}">
				<label for="offier">Catgeroy</label>

				<select name="offier" id="offier">
			
					<option value="0">no offier</option>
					<option value="1">offier</option>

				</select>

				<span class="text-danger">{{$errors->first('offier')}}</span>
			        </div>
 


			           <div class="form-group {{$errors->has('image')?'has-error':''}}">
				<label for="image">image</label>
				<input type="file" name="image" id="image"  class="form-control" >
				<span class="text-danger">{{$errors->first('image')}}</span>
			           </div> 

                         <div class="form-group {{$errors->has('spl_price')?'has-error':''}}">
				<label for="spl_price">sale price</label>
				<input type="text" name="spl_price" id="spl_price"  class="form-control" >
				<span class="text-danger">{{$errors->first('spl_price')}}</span>
			             </div>
<button type="submiy" class="btn btn-info">Add product</button>
		</form>	
	</div>
</div>
        
        </main>
@Endsection

resources/views/admin/product/index.blade.php
@extends('admin.master')
@section('title','List Product')
@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <h1>List Product</h1>
        <div class="large-3 columns">

        <select name="filter_id" id="filterValue">
              <option value="ASC">ASC</option>
              <option value="DESC">DESC</option>

        </select>


    </div>
   <!--  <form id="A" method="post" action="{{url('sreach')}}">
{{csrf_field()}}    <input type="text" name="seac" id="v">
    <button type="submit" id="s"  value="">sub</button>
    </form> -->
 <div class="form-group">
      <input type="text" name="search" id="search" class="form-control" placeholder="Search Customer Data" />
     </div>
           <h3 align="center">Total Data : <span id="total_records"></span></h3>

<table class="table table table-striped table-bordered" id="aa">
	<tr> 
		<thead>
		<td>id</td>
	    <td>image</td>
		<td>name</td>
		<td>price</td>
		<td>cager</td>
		<td>contoller</td>
</thead>

	</tr>

	<tbody id="ss" >
@foreach($products  as $product)
	<tr>
<td>{{$product->id}}</td>
<td><img src="{{url('image',$product->image)}}" width="80" height="80"></td>
<td>{{$product->pro_name}}</td>
<td>{{$product->pro_price}}</td>
<td>cate</td>
<td>
	<form action="{{route('product.destroy',$product->id)}}" method="post">
	{{csrf_field()}}
	{{method_field('DELETE')}}
	<input type="submit" class="btn btn-danger" value="DELETE"> 
    </form>
 <a class="btn btn-success" href="{{route('product.edit',$product->id)}}">Edit</a>
</td>
	</tr>
	@endforeach
</tbody>
</table>
<div id="localSearchSimple"></div>


        
        </main>
        <script type="text/javascript" src="{{asset('js/jquery.js')}}"></script>

`


          <script>
    $(document).ready(function(){

    $('#filterValue').change(function(){
          var teach_id = $('#filterValue option:selected').attr('value');
            
      $.ajax({
    type:'GET',
        url:"{{url('newsa')}}/"+  teach_id ,
    dataType:'json',

    success:function(data){
    	console.log(data.length);
    	var a='';
    	a+="<thead>";
		a+="<td>id</td>";
	    a+="<td>image</td>";
		a+="<td>name</td>";
		a+="<td>price</td>";
		a+="<td>cager</td>";
		a+="<td>contoller</td>";
		a+="</thead>";

           for(var i=0;i<data.length;i++){
	
a+="<tr>";
a+="<td>";
a+=data[i].id;
a+="</td>";
a+="<td>";
a+="<img src='image/"+data[i].image+"'  width='80' height='80'>";  
a+="</td>";
a+="<td>";
a+=data[i].pro_name;
a+="</td>";
a+="<td>";
a+=data[i].pro_price;
a+="</td>";
a+="<td>";
a+=data[i].id;
a+="</td>";
a+="<td>";
a+="<form action='{{route('product.destroy',"+data[i].id+")}}' method='post'>";
 a+='{{csrf_field()}}';
 a+='{{method_field("DELETE")}}';	
a+="<input type='submit' class='btn btn-danger' value='DELETE'> ";	
a+= "</form>";
a+="<a class='btn btn-success' href='{{route('product.edit',"+data[i].id+")}}'>Edit</a>";
a+="</td>";


a+="</tr>";
                               $("#aa").html(a);
   }
                                           $("#aa").html(a);


    },
   });  
alert(teach_id);
            
    });
return false;
      });

$(document).ready(function(){

 fetch_customer_data();

 function fetch_customer_data(query = '')
 {
  $.ajax({
   url:"{{ route('live_search.action') }}",
   method:'GET',
   data:{query:query},
   dataType:'json',
   success:function(data)
   {
    $('$ss').show();
    $('#ss').html(data.table_data);
    // $('#total_records').text(data.total_data);
   }
  })
 }

 $(document).on('keyup', '#search', function(){
  var query = $(this).val();
  fetch_customer_data(query);
 });
});
</script>

@Endsection