routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=> ['web' => 'auth']],function (){


Route::get('newsa/{id}', 'HomeController@orderByDrop');
Route::get('/live_search/action', 'HomeController@action')->name('live_search.action');

	Route::resource('product','product');
Route::resource('category','cate');
	Route::resource('events','eventsConroller');

	Route::get('home',function(){
if(Auth::user()->admin == 0){
	return view('home');
}else{
	$user=\App\User::all();
return 	 view('admin.index', compact('user'));

}
	});
		});

// fornt 
Route::get('/', 'FrontController@index');
Route::post('sreachpage', 'FrontController@sareac');
Route::get('mail', 'FrontController@maila');
Route::get('event', 'FrontController@events');
Route::get('About', 'FrontController@About');
Route::get('products', 'FrontController@product');
Route::get('cate/{id}', 'FrontController@cate');
Route::get('Detail/{id}', 'FrontController@Detail');
Route::get('read/{id}/{por}', 'FrontController@read');

Route::get('add/{id}', 'ca@addcart');
Route::get('cart', 'ca@index');
Route::get('remove/{id}','ca@destroy');
Route::PUT('/Cart/update/{id}','ca@update');
//paym
Route::post('pay', 'PaymentController@paywithpaypal');
Route::get('stauts','PaymentController@stauts');
Route::get('Canceled','PaymentController@Canceled');

app/event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class event extends Model
{
    //
}

resources/views/admin/events/create.blade.php
@extends('admin.master')
@section('title','Events')
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              data here
            </div>
          </div>
<div class="container">
<h1 class="text-center">Add event</h1>
<form method="post" action="{{url('events')}}" role="form"  enctype="multipart/form-data">
			{{csrf_field()}}
		<div class="row">
	
<div class="col-md-2">
	<label>Title Event</label>
</div>
<div class="col-md-10">
	
<input type="text" name="title" class="form-control" style="width: 100%;">

</div>
<br>

<br>
	
<div class="col-md-2">
	<label>Decription Event</label>
</div>
<div class="col-md-10">

<textarea name="decrption"  class="form-control" cols="140" rows="5"></textarea>
</div>
<br>
<div class="col-md-2">
	<label>DATA Event</label>
</div>
<div class="col-md-4">

<input type="date" name="data" class="form-control"><br>

</div><br>
<div class="col-md-2">
	<label>TIME Event</label>
</div>
<div class="col-md-4">

<input type="time" name="time" class="form-control"><br>
</div><br>
<div class="col-md-2">
	<label>name </label>
</div>
<div class="col-md-10">

<input type="text" name="name" class="form-control" style="width: 100%;"></div>
<br>
<div class="col-md-2">
	<label>image </label>
</div>
<div class="col-md-10">

<input type="file" name="asd" class="form-control" style="width: 100%;"></div>

</div><br>
</div><br>
<div class="text-center">
<input type="submit" class="btn btn-success " value="Add Events">
</div>
</form>
</div>
        
        </main>
@Endsection

resources/views/admin/events/index.blade.php
@extends('admin.master')
@section('title','Events')
@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              data here
            </div>
          </div>
<div class="container">
	<a href="{{url('events/create')}}" class="btn btn-info">Add Event</a>
	<table class="table table-responve">
		<thead>
		<tr>
				<th>photo</th>
				<th>data</th>
				<th>title</th>
				<th>time</th>
				<th>name</th>
				<th>decrption</th>
				<th>control</th>
				

		</tr>
</thead>
<tbody>
	@foreach($eve as $e) 
	<tr>
		<td><img src="{{url('image/events/',$e->photo)}}" width="80" height="80"></td>
		<td>{{$e->data1}}</td>
		<td>{{$e->title}}</td>
		<td>{{$e->time}}</td>
		<td>{{$e->name}}</td>
		<td>{{$e->decrption}}</td>
		<td><form action="{{route('events.destroy',$e->id)}}" method="post">
	{{csrf_field()}}
	{{method_field('DELETE')}}
	<input type="submit" class="btn btn-danger" value="DELETE"> 
    </form>
 <a class="btn btn-success" href="{{route('events.edit',$e->id)}}">Edit</a>
</td>


	</tr>
	@endforeach
</tbody>
	</table>
</div>

        
        </main>
@Endsection